### ISSUE TITLE
Add Trezor One support

### ISSUE THREAD

**Issue by joshieDo** [joshieDo/rust-trezor-api#4]
ref https://github.com/foundry-rs/foundry/issues/606

**Comment by prusnak** [comment]
The protocol is the same no matter whether you talk to Trezor Model One or Trezor Model T, so this seems like done on the `rust-trezor-api` level?

**Comment by Planxnx** [comment]
still found same issues
```
Trezor ethereum app requires at least version: ">=2.4.2"
```

it's cause Trezor Model One and Model T use separate versions[(Model T 2.5.3, Model One 1.12.1)](https://trezor.io/learn/a/firmware-changelog)

**Comment by prusnak** [comment]
> still found same issues

This is an issue with ethers-rs - opened a PR there: https://github.com/gakonst/ethers-rs/pull/2350

**Comment by prusnak** [comment]
> This is an issue with ethers-rs - opened a PR there: [gakonst/ethers-rs#2350](https://github.com/gakonst/ethers-rs/pull/2350)

This PR has been merged, Trezor Model One is now supported in ethers-rs.

This issue can be closed.
